### ISSUE TITLE
[1.16.5]Crash when entering the world

### ISSUE THREAD

**Issue by Kasualix** [ThinkingStudios/Litematica-Forge#1]
https://pastebin.ubuntu.com/p/4WpZdY96cm/

**Comment by TexBlock** [comment]
emm，1.16.5 的 mixin不知道怎么回事。

**Comment by Kasualix** [comment]
architectury 的 mixin support 我一直觉得挺迷惑的（

**Comment by TexBlock** [comment]
> architectury 的 mixin support 我一直觉得挺迷惑的（

archloom的问题？ mixin这东西没研究明白（x_x）

**Comment by Kasualix** [comment]
我也不太清楚 ~之前用architectury写mixin各种不顺手，后来就换正经forge mdk了~

**Comment by Kasualix** [comment]
草，我直接把它整个overwrite了，竟然跑成功了
插入点是第80行的那个吧？
https://pastebin.ubuntu.com/p/rC528D2wtQ/

**Comment by TexBlock** [comment]
> 草，我直接把它整个overwrite了，竟然跑成功了 插入点是第80行的那个吧？ https://pastebin.ubuntu.com/p/rC528D2wtQ/

这样的话兼容性怎么样

**Comment by Kasualix** [comment]
在我的1165mixin天堂里没出问题（
