### ISSUE TITLE
Cannot use model data for a level other than the current client level

### ISSUE THREAD

**Issue by videogamesrcool** [ThinkingStudios/Litematica-Forge#11]
Crash is below, I have no idea how to troubleshoot or fix it.

[crash-2023-06-18_13.06.07-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/11782272/crash-2023-06-18_13.06.07-client.txt)

**Comment by TexBlock** [comment]
Can not be reproduced when installed separately, probably because of conflicts between other mods and this mod.
