### ISSUE TITLE
installed with dawncraft modpack, works fine until, you bring up the material list, then it just bricks the world and crashing constantly

### ISSUE THREAD

**Issue by Gotyourdetailz** [ThinkingStudios/Litematica-Forge#13]
[crash-2023-06-29_07.05.53-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/11909967/crash-2023-06-29_07.05.53-client.txt)

**Comment by Gotyourdetailz** [comment]
I want to be more thorough, so I'll try to explain more, I created a new world to test out forgematica, I could load a schematic, but when I did (m+L) to get the material list, it crashed and completely bricked the world, i guess I could just not look at the material list thats fine, I technically only need to see the schematic its self, but then another problem came up, when I tried to load a world that I had days in(like a world that ive played for awhile) I couldn't even load into it, it said saving world instantly and crashed, then I disabled the mod and the dependency library for it and the world was completely bricked I load into anymore even with the mod disabled, luckily I had a backup. I hope that was enough to give an understanding.

**Comment by Gotyourdetailz** [comment]
I want to be more thorough, so I'll try to explain more, I created a new world to test out forgematica, I could load a schematic, but when I did (m+L) to get the material list, it crashed and completely bricked the world, i guess I could just not look at the material list thats fine, I technically only need to see the schematic its self, but then another problem came up, when I tried to load a world that I had days in(like a world that ive played for awhile) I couldn't even load into it, it said saving world instantly and crashed, then I disabled the mod and the dependency library for it and the world was completely bricked I couldn't load into it anymore even with the mod disabled, luckily I had a backup. I hope that was enough to give an understanding.

**Comment by SkpC9** [comment]
I have similar problem with Create mod. Currently you can try [this port](https://github.com/AwangLL/litematica-forge), but only for 1.18.2

**Comment by SkpC9** [comment]
If a schematic only contains vanilla block, everything works fine. If it contains vanilla block and 1 cogwheel from create, no issue too. But If there are 2 cogwheels, or 1 cogwheel + 1 fluid tank, or 1 cogwheel + 1 chute(I only tested those), the game will crash when I check materials, also crash when using easyplacemode to place the second block from create mod.
[crash-2023-07-02_19.54.08-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/11929517/crash-2023-07-02_19.54.08-client.txt)

**Comment by TexBlock** [comment]
I saw it, but I don't know what mod this problem is incompatible with now, I'm troubleshooting.

**Comment by SkpC9** [comment]
I tested 1.20.1 with create 0.5.1d, this mod works with no issue now

**Comment by Kasualix** [comment]
Be fixed in https://github.com/ThinkingStudios/Litematica-Forge/commit/5aee50707c6fe2c55ae415b411a568c36e33a950
