### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by sussymmm** [ThinkingStudios/Litematica-Forge#14]
can't enter the game always crash
[latest.log](https://github.com/ThinkingStudios/Litematica-Forge/files/11924800/latest.log)

**Comment by sussymmm** [comment]
[crash-2023-06-07_18.19.59-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/11924802/crash-2023-06-07_18.19.59-client.txt)

**Comment by TexBlock** [comment]
use latest mafglib version

**Comment by sussymmm** [comment]
[latest.log](https://github.com/ThinkingStudios/Litematica-Forge/files/11925635/latest.log)
still not working
