### ISSUE TITLE
Mod will not show up in forge launcher nor launch the game if in the mod folder

### ISSUE THREAD

**Issue by micchukelz** [ThinkingStudios/Litematica-Forge#22]
Attempted to test if this was working right got both mods needed and launched the most recent Minecraft patch on forge launcher and could not get the mods to show up in the under the "modpack" profile or in the forge launcher in general, through looking at the mod list, or trying to search the mod through the launcher to attempt a more proper download. And when I attempted to just launch the game it crashed. I haven't messed with mods for a while so I don't know if i missed a step or something.

**Comment by Arklan14** [comment]
I have a similar problem, it doesn't matter if there is no other mod loaded, the game doesn't open, it's version 1.19.2

**Comment by TexBlock** [comment]
> Attempted to test if this was working right got both mods needed and launched the most recent Minecraft patch on forge launcher and could not get the mods to show up in the under the "modpack" profile or in the forge launcher in general, through looking at the mod list, or trying to search the mod through the launcher to attempt a more proper download. And when I attempted to just launch the game it crashed. I haven't messed with mods for a while so I don't know if i missed a step or something.

can you give me a crash report?
