### ISSUE TITLE
Material List's Missing Count doesn't update

### ISSUE THREAD

**Issue by SuperFreak504** [ThinkingStudios/Litematica-Forge#23]
In the material list, the "Missing" count for blocks doesn't update when you have then in your inventory (e.g. it stays at 24 when you need to have 24 blocks even though you already have the 24 blocks in the inventory)

**Comment by TexBlock** [comment]
> In the material list, the "Missing" count for blocks doesn't update when you have then in your inventory (e.g. it stays at 24 when you need to have 24 blocks even though you already have the 24 blocks in the inventory)

Can you give me a log?
