### ISSUE TITLE
[suggestion]   About sharing schematics

### ISSUE THREAD

**Issue by fenlincao** [ThinkingStudios/Litematica-Forge#27]
well,I would really like you to add schematic sharing, which is very useful for multi-party builds.
In fact, fabric already has a mod for it, called **Syncmatica**, so maybe it just needs to be ported to forge.
Finally, I hope you can add this function, I need it so much, thank you very much!

**Comment by TexBlock** [comment]
Syncmatica is in plan

**Comment by fenlincao** [comment]
thank you!
