### ISSUE TITLE
personal question about contact

### ISSUE THREAD

**Issue by TheVirusNVGM** [ThinkingStudios/Litematica-Forge#29]
I didn’t find your discord channel or your social networks, so I have a couple of questions about your work, where can I contact you?

**Comment by TexBlock** [comment]
I don't use discord much (although I have an account) because it can be a bit difficult for me (it has to do with the internet environment in China), but of course you can email me if you want to contact me (2206114068@qq.com) or issues(?).

**Comment by TheVirusNVGM** [comment]
okey, i I wrote to you by email, but unfortunately there is no answer, can I find out when you have time, or whether the letter has arrived at all, or here you can answer more often?
