### ISSUE TITLE
Forgematica 1.16.5 needs Malilib which doesn't work on Forge..

### ISSUE THREAD

**Issue by LastKnight31** [ThinkingStudios/Litematica-Forge#37]
Loading Forgematica on Forge 1.16.5 bring up the error, 'Forgematica needs Malilib 0.1.0 or higher'.. after installing Malilib, Minecraft wont load. Malilib is a Fabric mod and Forgematica is supposed to be a Forge port.. With Malilib installed, Minecraft hangs while loading.

**Comment by samoht4** [comment]
I have this issue in 1.19.2 as well.

EDIT:  You just need to install the oldes version of the mafglib mod you can.

**Comment by TexBlock** [comment]
This has been fixed in the version just released.
