### ISSUE TITLE
failed schematic load

### ISSUE THREAD

**Issue by Pikldoornob** [ThinkingStudios/Litematica-Forge#39]
every time i try to load a schematic it says failed to load schematic https://mclo.gs/8AHnsu0

**Comment by ForgeLoverAndUser** [comment]
For some odd reason it seems like Mixin is causing problems for people. I dont know if its a resource by the same name or what but I think its mixin interfering somehow. This is shown at 19:38:56 when it says:

"[main/ERROR] [mixin/]: litematica.mixins.json:compat.MixinIForgeBlockEntity: Interface mixin contains a non-public method!"

The only thing i can think of is uninstalling Mixin if possible.

**Comment by TexBlock** [comment]
It could be a mod conflict.

**Comment by TexBlock** [comment]
Can you send me a schematic file to test?
