### ISSUE TITLE
Forgematica is not 100% working

### ISSUE THREAD

**Issue by Wintertjess** [ThinkingStudios/Litematica-Forge#45]
If i hold a stick in my hand, there is nothing in the left corner 

![image](https://github.com/ThinkingStudios/Litematica-Forge/assets/145144033/8cdba7fe-4e78-41b5-b848-ce849f8e48c6)
 

I cant pres I so i can see wich block it is

**Comment by TexBlock** [comment]
minecraft version? mod version?

**Comment by Wintertjess** [comment]
It is 1.20.1 and the mod version is forgematica-0.1.3-mc1.20.1.jar

**Comment by TexBlock** [comment]
mafglib issue, fixed in mafglib `0.1.8-mc1.20.1`
