### ISSUE TITLE
Using Forgematica on a 1.20.1 server

### ISSUE THREAD

**Issue by CallumFrost** [ThinkingStudios/Litematica-Forge#50]
Hi, so this is my first time using a schematic mod for minecraft and im wanting to use it to build Grians' season 6 Hermitcraft house. but cant see any keybinds or folders to use the mod. Any help?

**Comment by jade-clarke** [comment]
Hey @CallumFrost! As this repo is for the forge port for the Litematica mod, please refer to the documentation for Litematica. Basic instructions can be found on the curseforge page for the mod, as well as breakdowns of how to use it can be found on YouTube or even on Reddit! I hope this helps :)
