### ISSUE TITLE
Crashes constantly, 

### ISSUE THREAD

**Issue by AngelAether** [ThinkingStudios/Litematica-Forge#59]
[crash-2024-04-24_20.11.46-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/15099370/crash-2024-04-24_20.11.46-client.txt)

I don't know what else to go here.

**Comment by Kxuan** [comment]
Build [MaLiLib-Forge](https://github.com/ThinkingStudios/MaLiLib-Forge) and install the newest version to fix this problem.

You can use my build (if you trust me)
[MaFgLib-0.1.4-mc1.20.zip](https://github.com/ThinkingStudios/Litematica-Forge/files/15160338/MaFgLib-0.1.4-mc1.20.zip)
