### ISSUE TITLE
Forgematica works but doesn't respond at all.

### ISSUE THREAD

**Issue by LeoWyze** [ThinkingStudios/Litematica-Forge#60]
Written with the help of a translator.
The situation is this, I’m playing on version 1.20.1, I installed Forgematica version 0.1.3 and MaFgLib 0.1.9, the game started, I went into the creative world to check and the mod does not react at all. It is in the list of mods, it can be configured, the mod is in the F3 panel, but it does not respond to the stick or any keys.
I thought there was a mod conflict, I deleted everything except Forgematica and MaFgLib, no changes.

**Comment by TexBlock** [comment]
update Forgematica to 0.1.4

**Comment by LeoWyze** [comment]
Thank you, I solved the problem. I previously downloaded from CurseForge, and did not see the new version.

**Comment by TexBlock** [comment]
> Thank you, I solved the problem. I previously downloaded from CurseForge, and did not see the new version.

The modpublisher I configured seems to have a bit of a problem on the CF side, but I don't want to push it all over again at the moment, the next version should upload successfully.
