### ISSUE TITLE
Cannot open menus or use shortcuts in 1.20.1

### ISSUE THREAD

**Issue by Taidakun** [ThinkingStudios/Litematica-Forge#61]
Using mod version 0.1.3 for Minecraft 1.20.1, I can't seem to open any menu. 

Mod is installed properly, game is launching just fine, the mod appears in the mod list and I can access to its settings through Mod Menu, but nothing happen when I press M, or try any action with the stick; tried to rebind to other keys with no success either. 
Is there a list of known incompatibilities that might cause this ? We're running a bunch of mods, so my first guess is that, but I can't seem to find any specific information about that.

Cheers !

**Comment by imposd** [comment]
I was having the same issue where the mod was loading, but not actually working in the game. Using `0.1.8-mc1.20.1 MaFgLib` [beta release](https://www.curseforge.com/minecraft/mc-mods/mafglib/files/5068815), with `0.1.3 of Forgematica` worked for me, using the latest release of MaFgLib did not

**Comment by TexBlock** [comment]
use latest version in modrinth (curseforge version is broken, next version will fix)
