### ISSUE TITLE
Critical Error on forge 1.19

### ISSUE THREAD

**Issue by ghost** [ThinkingStudios/Litematica-Forge#63]
Hey, 

I have an issue with the 1.19 version of the mod.
I have Forge 1.19 and downloaded : 
- Forgematica 0.1.8-mc1.19.2 (Supports Forge 1.19-1.19.2)
- MaFgLib 0.1.10-mc1.19.2 (Supports Forge 1.19-1.19.2)

And when I try to start my solo game or try to connect to 1.19 server I got this error : 
![image](https://github.com/ThinkingStudios/Litematica-Forge/assets/57097865/cbd85793-4ac4-47e9-8853-52eaa2ed0c3d)

I removed all other 1.19 mods in my folder, there is only the two.

**Comment by TexBlock** [comment]
log?
