### ISSUE TITLE
1.18.2 Vault Hunters 3rd Edition loading error

### ISSUE THREAD

**Issue by MeowingInsanely** [ThinkingStudios/Litematica-Forge#67]
Forgematica Version: **0.1.8-mc1.18.2 (Beta)**
MaFgLib Version: **0.1.12-mc1.18.2**

Playing with this pack on ATLauncher: https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2

Error says:
Forgematica (forgematica encountered an error during the sided_setup event phase
java.lang.NoClassDefFoundError: fi/dy/masa/malilib/compat/forge/ForgePlatformUtils

Crash Report:
[crash-2024-05-26_18.18.27-fml.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/15447076/crash-2024-05-26_18.18.27-fml.txt)

**Comment by TexBlock** [comment]
see: https://github.com/ThinkingStudios/MaLiLib-Forge/issues/44

The mafglib part of the code is being refactored, please roll back the mafglib version to `0.1.10-mc1.18.2`

**Comment by TexBlock** [comment]
fixed
