### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by orkrs** [ThinkingStudios/Litematica-Forge#7]
Error when using the mod.
https://www.dropbox.com/s/zkj7o5tji5u59o0/Screenshot_30.png?dl=0

**Comment by TexBlock** [comment]
Sorry, I can't access this link :(
You can drag and drop files directly into the Write box

**Comment by orkrs** [comment]
> Sorry, I can't access this link :( You can drag and drop files directly into the Write box

The Mod File C:\Users\McPatison\AppData\Roaming\.minecraft\mods\forgematica-0.1.4-mc1.17.1.jar has mods that were not found - This Error

**Comment by TexBlock** [comment]
Fixed in [0.1.4fix-mc1.17.1](https://modrinth.com/mod/forgematica/version/0.1.4fix-mc1.17.1)
