### ISSUE TITLE
GUI not showing when holding stick

### ISSUE THREAD

**Issue by ergilly** [ThinkingStudios/Litematica-Forge#73]
Mod is all working, can use all the functionality, but the GUI is not showing when holding the correct item. Have tried swapping the item in the config, have tried enabling and disabling rendering and overlay etc. nothing has fixed.

**Comment by TexBlock** [comment]
> Mod is all working, can use all the functionality, but the GUI is not showing when holding the correct item. Have tried swapping the item in the config, have tried enabling and disabling rendering and overlay etc. nothing has fixed.

minecraft version？ forge version?

**Comment by ergilly** [comment]
1.20.4 
Neoforge 20.4.233
MaFgLib-0.1.7-mc1.20.4
Forgematica-0.1.4-mc1.20.4

**Comment by TexBlock** [comment]
mafglib issue, fixed
