### ISSUE TITLE
Cannot open gui

### ISSUE THREAD

**Issue by ljouhault** [ThinkingStudios/Litematica-Forge#74]
Hello, i find several tutorial saying the gui was open with M but it doesn't seems to work, i also don't see any related keybinds in the control. The mod is loaded, when i use a stick i use the basic selection functions so i know it's working, but i just cannot seem to open the gui to scan ore past schematic.

**Comment by ljouhault** [comment]
I'm on forge 1.19.2

**Comment by TheAshenWolf** [comment]
Check if you don't have any conflicting keybinds on [M]. The menu would not open for me until I unbound everything from it (At least on 1.20.1, but should work on 1.19.2 as well)

**Comment by ljouhault** [comment]
I checked, there is nothing set on the M key.
But i don't see the keybind for this mod either, isn't it supposed to show up in the controls ?

**Comment by TheAshenWolf** [comment]
It does not show up in the key bindings, no.

**Comment by ljouhault** [comment]
maybe but the M key is still supposed to do something and for me it doesn't

**Comment by ljouhault** [comment]
Alright for those who might get the same issue, i was on an azerty keyboard, and the gui is not bind to the letter M but to the key that happened to be the letter M on a qwerty keyboard, so i actually had to press "?".

This is precisely why mods keybinds are supposed to be configurable through the control menu.
