### ISSUE TITLE
its just not working

### ISSUE THREAD

**Issue by ranihuzainimbatsil69** [ThinkingStudios/Litematica-Forge#75]
i cant see it in my keybinds but its in my modpack

**Comment by TheAshenWolf** [comment]
Litematica never shows in the keybinds; the default keybind to open the menu is [M]. Additionally, you use a stick (and ctrl + scroll wheel to change its mode). You can change the keybinds within the Litematica menu. 

Here is a random video tutorial if you are into that: https://www.youtube.com/watch?v=KFzyNtyN8qI

**Comment by TexBlock** [comment]
see #61
