### ISSUE TITLE
1.18.1：Error loading class: net/minecraft/core/Holde

### ISSUE THREAD

**Issue by wett5177** [ThinkingStudios/Litematica-Forge#77]
After modifying the fml and forge versions of the mods.toml file
1.18.1 versions encountered errors during game startup
or 【[main/ERROR]: forgematica.mixins.json:compat.MixinIForgeBlockEntity: Interface mixin contains a non-public method!】
[minecraft-exported-crash-info-2024-06-28T01-30-47.zip](https://github.com/user-attachments/files/16018906/minecraft-exported-crash-info-2024-06-28T01-30-47.zip)

**Comment by TexBlock** [comment]
use latest version

**Comment by TexBlock** [comment]
plz use 1.18.2

**Comment by wett5177** [comment]
thank i must to use v1.18.1
if necessary i will try to fix it
