### ISSUE TITLE
Cannot open menus when change the key 'M' to other key

### ISSUE THREAD

**Issue by whystars** [ThinkingStudios/Litematica-Forge#79]
In version 1.20.1, change the fixed 'M' key to invoke the main menu to a setting where no other keys can open the main menu.

Minecraft version:1.20.1
Mod version:0.1.5 for 1.20.1
MaFgLib version:0.1.11 for 1.20.1

Why???

**Comment by TexBlock** [comment]
Unable to reproduce the problem
