### ISSUE TITLE
Network Protocol Error-1.21-Realms

### ISSUE THREAD

**Issue by GanmaZ** [ThinkingStudios/Litematica-Forge#80]
Doesn't allow you to enter minecraft realms, 1.21 Neoforge.
Litematica-Neoforge Version: 0.1.6-mc1.21
MaFgLib: 0.1.14-mc1.21

**Comment by TexBlock** [comment]
Theoretically, realms is not supported at the moment, because realms is vanilla server.

**Comment by TexBlock** [comment]
Of course this is a MaFgLib network communication issue
