### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kirillka77734** [ThinkingStudios/Litematica-Forge#83]
https://mclo.gs/FqW49UQ
and
https://mclo.gs/LskpjL9

a window pops up when downloading into minecraft

![image](https://github.com/user-attachments/assets/4d36fdd6-b512-4fdd-ba1b-5d7cae81ed9f)

**Comment by Barerock** [comment]
Look at the other issues first. Use modrinth versions of the mods.

**Comment by Barerock** [comment]
All of the information in the github from the dev shows that we're supposed to use the modrinth versions; however, those are also broken. Either take the mod down while it's completely and utterly non-functional or put a warning on the page, AND here. It's annoying spending 40 minutes troubleshooting a mod that simply isn't made right.

**Comment by Barerock** [comment]
And now to spend another 40 minutes fixing my default settings because this mod makes forge load incorrect, resetting EVERYTHING.

**Comment by TexBlock** [comment]
Please roll back mafglib to 0.1.12 for now, mafglib changed something yesterday.I'll release an update to fix this later for mods that depend on mafglib.

**Comment by TexBlock** [comment]
fixed
