### ISSUE TITLE
Crash right after world load with Embeddium

### ISSUE THREAD

**Issue by ssfwuu0721** [ThinkingStudios/Litematica-Forge#92]
Now it's ok with Valkyrien Skies, but crashes with Embeddium

**Comment by TexBlock** [comment]
crash report logs?

**Comment by Barerock** [comment]
Here:
[crash-2024-09-08_12.52.48-server.txt](https://github.com/user-attachments/files/16923010/crash-2024-09-08_12.52.48-server.txt)
[latest.log](https://github.com/user-attachments/files/16923011/latest.log)

This suddenly started happening, I've had the mod installed for a long time now. I went to a cherry forest in preloaded chunks last night, but now logging in causes this.

**Comment by Barerock** [comment]
v0.1.6 1.20.1, I have updated to 0.1.7 now and the same crash occurred. Logs say it's connector related, but that might just be a fluke.

**Comment by Barerock** [comment]
This crash still occurs without forgematica, disregard

**Comment by ssfwuu0721** [comment]
emmm, in fact i found embeddium, valkyrien, litematica, any two of them are okey, but can't work together.
and fabric litematica already has the problem, sorry for that..
