### ISSUE TITLE
Forgematica not loading on 1.21.1

### ISSUE THREAD

**Issue by ShipHeatRook** [ThinkingStudios/Litematica-Forge#93]
Hello! First of all, thank you for creating a mod I've been constantly using in several past servers!
Yesterday I found out that Forgematica apparently doesn't seem to load on Minecraft 1.21.1. Here are the versions I'm using:

Forgematica 0.1.11
MaFgLib 0.1.22
Badpackets 0.8.1

Badpackets appears in the mod list, yet MaFgLib and Forgematica don't. I also get no errors on load, as if the mods weren't even there to begin with. Any ideas about what I could try?

**Comment by TexBlock** [comment]
@ShipHeatRook Can't reproduce it, please post the log.
