### ISSUE TITLE
Color overlays flickering

### ISSUE THREAD

**Issue by Chrissiecake** [ThinkingStudios/Litematica-Forge#94]
https://github.com/user-attachments/assets/31b5f3b8-29bd-4a16-9a76-59b53c892bfa
Color overlays flicker at certain angles, particularly when looking down. I've tried changing Minecraft's graphics settings and removing all texture packs, and my graphics drivers are up to date. I've tried different versions of both Forgematica and MaFgLib. This happens with all schematics, and all color overlays regardless of transparency. I've had this happening for several months now, so it's not a new issue.
Using version Forgematica 0.1.7-mc1.20.1 and 0.1.13-mc1.20.1 of MaFgLib on Minecraft 1.20.1. with a NIVIDIA GeForce RTX 3060 Laptop GPU.
Apologies for any formatting issues, I'm new to GitHub.

**Comment by TexBlock** [comment]
non-replicable
